#!/bin/bash

# Required environment variable: REPOSITORY_URL
VERSION=$(grep 'Version: ' DEBIAN/control|cut -d' ' -f2)
DESCRIPTION=$(grep 'Description: ' DEBIAN/control|cut -d' ' -f2-)

i686_pkg=${CI_PROJECT_NAME}_$VERSION_arch_i386.deb
amd64_pkg=${CI_PROJECT_NAME}_$VERSION_arch_amd64.deb

i686_url=$REPOSITORY_URL/pool/main/${CI_PROJECT_NAME:0:1}/${CI_PROJECT_NAME}/$i686_pkg
amd64_url=$REPOSITORY_URL/pool/main/${CI_PROJECT_NAME:0:1}/${CI_PROJECT_NAME}/$amd64_pkg

i686_md5=$(wget $i686_url -O-|md5sum -|cut -d' ' -f1)
amd64_md5=$(wget $amd64_url -O-|md5sum -|cut -d' ' -f1)

tmp=$(mktemp -d)
cd $tmp
git clone ssh+git://aur@aur.archlinux.org/${CI_PROJECT_NAME}.git
cd $CI_PROJECT_NAME
echo> PKGBUILD
echo>>PKGBUILD '# Maintainer Alexis Pereda <alexis@pereda.fr>'
echo>>PKGBUILD
echo>>PKGBUILD "pkgname=$CI_PROJECT_NAME"
echo>>PKGBUILD "pkgver=$VERSION"
echo>>PKGBUILD 'pkgrel=1'
echo>>PKGBUILD 'pkgdesc="'$DESCRIPTION'"'
echo>>PKGBUILD "arch=('i686', 'x86_64')"
echo>>PKGBUILD 'url=""'
echo>>PKGBUILD "license=('GPL')"
echo>>PKGBUILD 'depends=()'
echo>>PKGBUILD "source_i686=(\"$i686_url\")"
echo>>PKGBUILD "md5sums_i686=($i686_md5)"
echo>>PKGBUILD "source_x86_64=(\"$amd64_url\")"
echo>>PKGBUILD "md5sums_x86_64=($amd64_md5)"
echo>>PKGBUILD
echo>>PKGBUILD 'package() {'
echo>>PKGBUILD '  msg2 "Extracting the data.tar.xz"'
echo>>PKGBUILD '  bsdtar -xf data.tar.xz -C "$pkgdir/"'
echo>>PKGBUILD '}'

mksrcinfo

git add -A
git commit -m "[$VERSION]"
git push
